- docs/configuration.rst
- tests/test_cli.py
- yamllint/cli.py
- yamllint/linter.py
This PR adds a strict mode which returns a non-zero exit code when there are only warnings.
> Strict mode

- tests/test_module.py
- yamllint/__main__.py
Allows execution using python -m yamllint
> Add __main__

- tests/test_cli.py
- yamllint/cli.py
This does the same as your solution :wink:
> Use argparse mutually_exclusive_group for --config-file and --config-data

- .pre-commit-hooks.yaml
- docs/index.rst
- docs/integration.rst
A quick pull request to just add the new pre-commit hook file format, as also some documentation in README for how to use it.
> Update pre-commit hook

- .gitignore
- tests/rules/test_quoted_strings.py
- yamllint/conf/default.yaml
- yamllint/rules/__init__.py
- yamllint/rules/quoted_strings.py
* taken from https://github.com/adrienverge/yamllint/pull/110 (submitted by @jurajseffer)
* small fix for generic strings
* fixes for comments from @adrienverge
> Feature: Quoted strings value rule

- yamllint/config.py
- yamllint/linter.py
- yamllint/rules/document_end.py
- yamllint/rules/indentation.py
> Use isinstance(x, y) instead of type(x) == y

- tests/test_cli.py
- yamllint/cli.py
- If yaml files are given as arguments, parses the files first and then stdin.
- If no yaml files are given, just checks stdin.
- If yamllint is run without any files or --stdin option, just finishes without errors.
I found the option --stdin to be more reasonable than with no args. Mainly when automating yamllint from scripts.
Tried to minimize changes to base code. But had to create a function `show_problems` which is called for files and for stdin with slightly different arguments. This function is basically copy/paste of existing code.
Also moved a lot of code from the try/exception to the else block, so that it only catches on open(file). You might want to check on that (are there other reasons for an EnvironmentError exception?).
> Add command line option --stdin to read from standard input.

- setup.py
- yamllint/cli.py
- yamllint/rules/colons.py
- yamllint/rules/indentation.py
Sort import orders reported by [flake8-import-order](https://github.com/PyCQA/flake8-import-order).
> Sort import orders

- docs/configuration.rst
- yamllint/cli.py
> feat: Support reading config from .yamllint.yml and .yamllint.yaml

- docs/integration.rst
* pre-commit show warning for unsupported key (sha)
* Demonstrate how to use custom yamllint
> docs: Fix pre-commit config file

- tests/rules/test_quoted_strings.py
- yamllint/rules/quoted_strings.py
> Fix quoted-strings rules not working for string values matching scalars

- tests/rules/test_quoted_strings.py
- yamllint/rules/quoted_strings.py
> Add support for redundant quotes in quoted-strings rule

- CONTRIBUTING.rst
Closes https://github.com/adrienverge/yamllint/issues/263.
> Add contribution instructions in CONTRIBUTING.rst

- tests/test_cli.py
- yamllint/config.py
> Do no match directories that look like YAML files

- docs/configuration.rst
- tests/rules/test_key_ordering.py
- tests/test_cli.py
- yamllint/cli.py
- yamllint/config.py
- yamllint/rules/key_ordering.py
This reverts commit 9e90c77, because it caused a bug that affected
different people just after being released:
https://github.com/adrienverge/yamllint/issues/285
https://github.com/adrienverge/yamllint/issues/286
> Revert "Add global "locale" config option"

- docs/development.rst
> Add Python API usage example

- setup.cfg
- setup.py
Changes to simplify setup.py by moving its some packaging configurations into setup.cfg and add some meta data into setup.cfg.
> Changes to simplify setup.py and make packaging stuff easier to maintain

- tests/rules/test_octal_values.py
- yamllint/rules/octal_values.py
Fixes https://github.com/adrienverge/yamllint/issues/271#issuecomment-688237384.
> Prevent detection of 8 and 9 as octal values

- tests/rules/test_quoted_strings.py
- yamllint/rules/quoted_strings.py
Fixes #271.
This is my first Python contribution ever, please let me know if there's anything wrong :)
> Fix detecting strings with hashtag as requiring quotes

- docs/integration.rst
This was helpful for me in integrating `yamllint` with Arcanist. I followed the [SO post here](https://stackoverflow.com/questions/53527784/how-do-i-setup-yaml-linting-in-arcanist) and it worked perfectly. Just wanted to formalize this in the docs.
> Add configuration for integration with Arcanist

- .github/workflows/ci.yaml
https://github.com/actions/checkout
https://github.com/actions/setup-python
> ci: Update GitHub Actions

- .github/workflows/ci.yaml
- docs/configuration.rst
- docs/index.rst
- docs/quickstart.rst
- docs/text_editors.rst
- yamllint/rules/new_line_at_end_of_file.py
> Update redirecting links in docs

- yamllint/rules/float_values.py
RUF039 First argument to `re.compile()` is not raw string
> style: Apply ruff rule RUF039

- yamllint/cli.py
FURB188 Prefer `str.removeprefix()` over conditionally replacing with slice.
> Apply ruff/refurb rule FURB188

- tests/test_cli.py
PIE800 Unnecessary spread `**`
> Apply ruff/flake8-pie rule PIE800

- .github/workflows/tests.yaml
This is more logical and sets the ground for other GitHub Actions workflows, e.g. automated distribution releases.
> CI: Rename the GitHub Actions workflow file tests.yaml

- .github/workflows/publish.yaml
Closes https://github.com/adrienverge/yamllint/issues/721
> CI: Publish PyPI releases using GitHub Actions workflows

- docs/quickstart.rst
Closes https://github.com/adrienverge/yamllint/issues/733.
> docs: Add links to GitHub repository and releases

- tests/common.py
- tests/test_cli.py
Mostly [flake8-simplify (SIM)](https://docs.astral.sh/ruff/rules/#flake8-simplify-sim) rules.
> style: Apply assorted ruff rules
