adrienverge/yamllint

tests/rules/test_indentation.py, yamllint/rules/indentation.py
Previously, when the indentation rule blocked on an unexpected token,
the program crashed with something like:
File "/usr/lib/python3/dist-packages/yamllint/rules/indentation.py",
line 434, in check
assert context['stack'][-1].type == KEY
AssertionError
Instead, we prefer report the error as a regular `LintProblem` and
continue processing.
Fixes: #3
---
The following source -- although not loadable by pyyaml -- is valid
YAML:
{{key}}: value
This was processed badly by yamllint. The same for `[[value]]`,
`{{{{{moustaches}}}}}` or:
{[val,
{{key: val,
key2}}]}
This patch corrects it and add corresponding test cases.
Related-to: #3
=> Indentation: imbricated flows

tests/rules/test_line_length.py, yamllint/rules/line_length.py
Hi,
I found that the allow-non-breakable-words is not working as I expected (not sure if we have the same expectations!) with long URLs preceeded by '- ' instead of '# '.
The patch implements (test included) that expectation.
HTH,
Michele
PS: I came up with the use case using yamllint on Ansible playbooks
=> Patch allow-non-breakable-words on '-'

tests/test_cli.py, yamllint/cli.py
=> feat(cli): Colour output only on TTY

tests/rules/test_line_length.py, yamllint/conf/default.yaml, yamllint/conf/relaxed.yaml, yamllint/rules/line_length.py
Previously, the unbreakable line check only worked for array items (`- foo`) or comments (`# foo`): this branch extends it to also work with mapping values (`key: foo`).
=> line_length: Allow mapping values with long unbreakable lines

tests/rules/test_truthy.py, yamllint/rules/truthy.py
With this change, we don't require quotes for truthy values that are explicitely typed. For instance, the following examples are all considered valid:
```yaml
string1: !!str True
string2: !!str yes
string3: !!str off
encoded: !!binary |
True
OFF
pad==  # this decodes as 'N\xbb\x9e8Qii'
boolean1: !!bool true
boolean2: !!bool "false"
boolean3: !!bool FALSE
boolean4: !!bool True
boolean5: !!bool off
boolean6: !!bool NO
```
=> feat(truthy): Allow explicit types

setup.py
Found them installed in my `site-packages`, importable as `import tests` :scream:
Tested with:
```
In [2]: find_packages()
Out[2]: ['tests', 'yamllint', 'tests.rules', 'yamllint.rules']
In [3]: find_packages(exclude=['tests', 'tests.*'])
Out[3]: ['yamllint', 'yamllint.rules']
```
=> setup.py - don't distribute tests

tests/rules/test_braces.py, tests/rules/test_brackets.py, yamllint/conf/default.yaml, yamllint/rules/braces.py, yamllint/rules/brackets.py
This allows empty objects (e.g. `[]`, `{}`) to be handled separately from non-empty ones. In my case, I want `min-spaces-inside: 1` and `max-spaces-inside: 1` for braces and brackets, but I want empty items to have no spaces (`min-spaces-inside-empty: 0` and `max-spaces-inside-empty: 0`).
This has been done as backward-compatible as possible, defaulting the new settings to `-1` and using the non-empty configuration variable value in the the case of `-1`. Thus, users should see no difference in behavior of existing configurations unless one of the new variables is set.
=> Add min-spaces-inside-empty, max-spaces-inside-empty to braces and brackets

docs/text_editors.rst
Hi.
I've recently created Flycheck plugin which integrates YAMLint into Emacs. I'm waiting for MELPA acceptance, but in meantime it can be easily installed directly from my GitHub repository. This pull request adds information about that plugin to editors section of documentation.
Cheers.
=> Add information about Emacs integration

docs/integration.rst
Hi, after using yamllint with pre-commit I noticed the following:
```yaml
.pre-commit-config.yaml
2:1       warning  missing document start "---"  (document-start)
```
Maybe you can consider merging this :smile: 
cheers
=> fix yamllint error

tests/rules/test_indentation.py, yamllint/rules/indentation.py
If a key-value pair follows an empty list, i.e.:
```yaml
a:
-
b: c
```
yamllint will complain:
```
warning  wrong indentation: expected 2 but found 0  (indentation)
```
This is because it is expecting the second key to be a continuation of
the block entry above:
```yaml
a:
-
b: c
```
However, both are perfectly valid, though structurally different.
=> Fix indentation rule for key following empty list

yamllint/cli.py
Not all systems have `isatty` attribute on `sys.stdout` so check for
existance of attribute before checking value. Also don't use color in
Windows unless environ indicates support. Apparently, Windows can indicate
support by either the presence of `ANSICON` environ variable or if the
`TERM` environ variable is set to `ANSI`. Fixes #79.
No additional tests added, as the relevant tests use fcntl, which is a
Unix only lib. In fact, the tests won't even run in Windows (import error
for `fcntl` module in `test.cli.py`).
=> Better color support check.

docs/rules.rst, tests/rules/test_octal_values.py, yamllint/conf/default.yaml, yamllint/rules/__init__.py, yamllint/rules/octal_values.py
Hi, i want to add a new rule for checking the values should not be a octal number. like:
```
user-citycodes: 010
```
`010` is the city code of beijing. but in some system, it is converted to the decimal number `8`.
so if we add the config `octal-values: enable`. `user-citycodes: 010` will fail. but `user-citycodes: '010'` or `user-citycodes: 010,0571` will pass.
=> Feature: a new rule for checking octal numbers

.travis.yml
See issue https://github.com/PyCQA/flake8-import-order/issues/149
=> CI: Fix failing tests for Python 3.6 because of flake8-import-order

tests/rules/test_key_duplicates.py, yamllint/rules/key_duplicates.py
fixes #88 
LMK if you spot anything fishy. I couldn't dedicate much time to tracing back so my method may be wrong --- but all unit tests pass so if there is something wrong, it's not covered.
=> 88 anchor references seen as duplicate key

docs/configuration.rst
[Solved this issue](https://github.com/metacloud/molecule/issues/1228) and want to update the documentation. Occurs when yamllint is used with molecule.
=> removed leading slashes from 'ignore: |' directories

yamllint/rules/truthy.py
I like the 'truthy' rule but its documentation and message have confused several of my colleagues (e.g. @flatnine and @seporaitis ). I've tried rewriting its docs and message to be clearer.
=> Clarify documentation on the 'truthy' rule

yamllint/parser.py
There is a backwards-incompatible change in PyYAML that induces a crash
if `check_token()` is not called before `peek_token()`. See commit
a02d17a in PyYAML or https://github.com/yaml/pyyaml/pull/150.
Closes #105.
=> parser: Fix crash with latest PyYAML

README.rst
I noticed that yamllint isn't in the base repo for CentOS 7, so I added a note about requiring EPEL.
=> EPEL on CentOS

.travis.yml
Because installing dependencies for `coveralls` now fails with:
Collecting pycparser (from cffi>=1.7->cryptography>=1.3.4; python_version <= "2.7" and extra == "secure"->urllib3[secure]; python_version < "3"->coveralls)
[...]
pycparser requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*' but the running Python is 2.6.9
=> CI: Fix tests failing on Travis for Python 2.6

tests/rules/test_quoted_strings.py, yamllint/rules/quoted_strings.py
Original implementation was completely broken. Documentation and actual
behavior were different. Numbers and booleans were detected as wrong, as
well as explicit types.
Fixes #136 and #130.
=> quoted-strings: Fix broken rule

tests/test_cli.py, yamllint/cli.py
Sometimes you want the output to be colored even if sys.stdout is not a tty. Example:
```bash
yamllint . | less -R
```
Therefore I added the argument `-f colored` or `--format colored` to force a colored output.
=> Add -f colored to force colors

.travis.yml
The `pkg_resources` package inside `setuptools` explicitly [disallows
Python 3.3](https://github.com/pypa/setuptools/commit/7392f01ffced3acfdef25b0b2d55cefdc6ee468a#diff-81de4a30a55fcc3fb944f8387ea9ec94):
if (3, 0) < sys.version_info < (3, 4):
raise RuntimeError("Python 3.4 or later is required")
It's time to drop support for 3.3.
=> CI: Drop Python 3.3 support

tests/rules/test_line_length.py, yamllint/rules/line_length.py
Some unicode characters span accross multiple bytes. Python 3 is OK with
that, but Python 2 reports an incorrect number of characters.
Related to https://github.com/adrienverge/yamllint/issues/146
---
Closes #146.
=> line-length, unicode and Python 2

.travis.yml, docs/configuration.rst, docs/disable_with_comments.rst, docs/quickstart.rst
=> Lint documentation with doc8

tests/test_config.py, yamllint/conf/default.yaml, yamllint/config.py, yamllint/rules/braces.py, yamllint/rules/brackets.py, yamllint/rules/colons.py, yamllint/rules/commas.py, yamllint/rules/comments.py, yamllint/rules/document_end.py, yamllint/rules/document_start.py, yamllint/rules/empty_lines.py, yamllint/rules/empty_values.py, yamllint/rules/hyphens.py, yamllint/rules/indentation.py, yamllint/rules/key_duplicates.py, yamllint/rules/key_ordering.py, yamllint/rules/line_length.py, yamllint/rules/new_lines.py, yamllint/rules/octal_values.py, yamllint/rules/quoted_strings.py, yamllint/rules/truthy.py
Before, it was required to specify all the options when customizing a
rule. For instance, one could use `empty-lines: enable` or `empty-lines:
{max: 1, max-start: 2, max-end: 2}`, but not just `empty-lines: {max:
1}` (it would fail with *invalid config: missing option "max-start" for
rule "empty-lines"*).
This was a minor problem for users, but it prevented the addition of new
options to existing rules, see [1] for an example. If a new option was
added, updating yamllint for all users that customize the rule would
produce a crash (*invalid config: missing option ...*).
To avoid that, let's embed default values inside the rules themselves,
instead of keeping them in `conf/default.yaml`.
This refactor should not have any impact on existing projects. I've
manually checked that it did not …
=> config: Do not require all rule options to be set

tests/rules/test_comments.py, yamllint/rules/comments.py
Some usages of YAML (like Ansible) supports running the file as a script.
Support (by default) an ignore-shebangs setting for the comments module.
Fixes #116 - comments rule with require-starting-space: true should special case shebang
=> Support ignoring shebangs

docs/quickstart.rst
See commit 05dfcbc "cli: Add command line option - to read from standard
input", cc @miguelbarao.
=> docs(cli): Add a paragraph about standard input

tests/rules/test_truthy.py, yamllint/rules/truthy.py
This MR implements optional exceptions for truthy rule. 
Example usage (ansible):
```yaml
---
rules:
line-length:
max: 160
level: warning
truthy:
allowed-values: ["yes", "no"]
```
Implemented in truthy rule by doing difference of sets of predefined banned values and configured allowed values.
Added 3 tests, all passed successfully.
Please feel free to review and suggest simplifications, or better variable names, which can be more standard and explanative.
Closes https://github.com/adrienverge/yamllint/issues/150
=> Enh/allowed truthy values/#150

yamllint/rules/truthy.py
Edit documentation for the `truthy` rule, in order to:
- add quotes to examples (`'yes'` instead of `yes`) to avoid
misconfigurations,
- group truthy values in the `allowed-values` option paragraph, for
easier reading.
---
@Lirt I realized that when reading https://yamllint.readthedocs.io/en/latest/rules.html#module-yamllint.rules.truthy, after merging your PR. Feel free to comment/edit or correct my English if needed!
=> truthy: Try to make docs on allowed-values more explicit

tests/rules/test_truthy.py, tests/test_config.py, yamllint/config.py, yamllint/rules/truthy.py
Allow rules to declare a list of valid values for an option.
For example, a rule like:
CONF = {'allowed-values': list}
... allowed any value to be passed in the list (including bad ones).
It is now possible to declare:
CONF = {'allowed-values': ['value1', 'value2', 'value3']}
... so that the list passed to the options must contain only values in
`['value1', 'value2', 'value3']`.
---
Make sure values passed in allowed values are correct ones. This is
possible thanks to previous commit, and should prevent users from
writing incorrect configurations.
---
@Lirt for info.
=> truthy: Validate options passed to 'allowed-values'

docs/quickstart.rst
Hi,
this diff adds the OpenBSD installation instructions only in docs/quickstart.rst.
Best regards.
=> add OpenBSD installation instructions

docs/configuration.rst
* A straight copy/paste of the existing example into the `.yamllint` file results in a `yamllint` error!
=> docs(configuration): improve `yaml-files` code example

tests/rules/test_octal_values.py, yamllint/conf/default.yaml, yamllint/rules/empty_values.py, yamllint/rules/octal_values.py
* Close #204 
---
@adrienverge This is the crux of the resolution.  What do you think about adding a note in the documentation, under each section (`empty-values` & `octal-values`)?  It could be used for the time being until existing users become informed that these values were in fact, not enabled.
=> fix(default.yaml): disable `empty-values` & `octal-values` by default

docs/disable_with_comments.rst, tests/test_yamllint_directives.py, yamllint/linter.py
Allow disabling of a file, even if it is invalid yaml by including `yamllint disable-file` in the first line.
=> Allow Disabling Non-Yaml Files

docs/configuration.rst, tests/test_cli.py, yamllint/cli.py
Add configuration option `output-verbosity` to enable output filtering by problem level.
Aims to solve #86.
=> Filter output by problem level

.travis.yml
As can be seen in https://travis-ci.org/adrienverge/yamllint/builds/631325436?utm_source=github_status&utm_medium=notification
The dependency, pathspec, requires Python '>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*' but the running Python is 3.4.8
This commit stops Travis building yamllint against 3.4 so that CI can pass again.
=> Disable building on python3.4

.travis.yml
Python 3.8 was released in October 2019.
=> CI: Run tests on Python 3.8

tests/test_cli.py, yamllint/cli.py
The fix is reasonably simple, to add the test that fails on Python 3 I also did some refactoring of `test_cli.py` setup. See the individual commits for full details.
=> Fix new-lines rule on Python 3

tests/rules/test_truthy.py, yamllint/rules/truthy.py
Fixes: #158
This PR adds `check-keys` option to the truthy rule.
If `check-keys` option is disabled the rule applies only to the values. Default is enabled.
=> truthy rule: add `check-keys` option

README.rst
Keep supporting Python 2.7 for one extra year after upstream dropped it:
https://www.python.org/doc/sunset-python-2/
=> docs: Sunset Python 2

tests/rules/test_quoted_strings.py, yamllint/rules/quoted_strings.py
And move only-when-needed tests at the end for readability.
---
The rule worked for values like:
```yaml
flow-map: {a: foo, b: "bar"}
block-map:
a: foo
b: "bar"
```
But not for:
```yaml
flow-seq: [foo, "bar"]
block-seq:
- foo
- "bar"
```
Also add tests to make sure there will be no regression.
Fixes: #208.
=> Fix quoted-strings rule broken on lists

tests/rules/test_quoted_strings.py
It is exactly the same tests as `test_quote_type_single()`.
---
It is exactly the same tests as `test_quote_type_any()`.
=> quoted strings: Remove redundant tests

tests/rules/test_quoted_strings.py, yamllint/rules/quoted_strings.py
Change implementation of `required: only-when-needed`, because
maintaining a list of `START_TOKENS` and just looking at the first
character of string values has proven to be partially broken.
Cf. discussion at https://github.com/adrienverge/yamllint/pull/246#issuecomment-612354097.
Fixes https://github.com/adrienverge/yamllint/issues/242 and https://github.com/adrienverge/yamllint/pull/244.
---
@ruipinge what do you think? Do you see problems / unhandled cases?
=> quoted-strings: Fix only-when-needed on corner cases

tests/rules/test_quoted_strings.py, yamllint/config.py, yamllint/rules/quoted_strings.py
---
For example it's possible to define a conf like:
```yaml
rule:
foo: [str],
bar: [int, bool, 'magic'],
```
---
Add ability to:
- require strings to be quoted if they match a pattern (PCRE regex)
- allow quoted strings if they match a pattern, while `require:
only-when-needed` is enforced.
Co-Authored-By: Leo Feyer (https://github.com/adrienverge/yamllint/pull/246)
=> quoted-strings: Add extra-required and extra-allowed options

tests/test_cli.py, yamllint/cli.py
Hey team-
This PR instructs the CLI to check the `YAMLLINTRC` environment variable for a global config path. For _most_ intents and purposes, this can be achieved with the `-c` flag, but I found a corner case where the environment variable is useful: I'd like to point my editor and my CI server at the same config file, and it's much easier to specify the variable once in something like a `.env` file than tweaking how both systems invoke `yamllint` individually.
I'm not married to the name "`YAMLLINTRC`"; please let me know if there's a better name (I've been working with pylint lately, so I think I subconsciously borrowed their convention). Also, please let me know if this is PR is the right place to make the corresponding update to the docs.
Thanks!
=> Option to specify config file with environment variable

setup.py
3.8 is now formally supported in .travis.yml
as of this commit.
=> Add Python 3.8 to PyPI/trove classifier data

docs/configuration.rst
Notes the new config file option from #255 in the docs.
=> Mention YAMLLINT_CONFIG_FILE in the documentation

tests/rules/test_comments.py, tests/rules/test_new_lines.py, yamllint/rules/comments.py
Pound-signs followed by a lone CRLF should not
raise if require-starting-space is specified and newlines are dos or disabled.
Adds three new passing test cases in addition to the fix:
```
$ coverage run --source=yamllint setup.py test -s tests.rules.test_comments.CommentsTestCase
test_empty_comment_crlf_disabled_newlines (tests.rules.test_comments.CommentsTestCase) ... ok
test_empty_comment_crlf_dos_newlines (tests.rules.test_comments.CommentsTestCase) ... ok
```
=> Bugfix: GH Issue #171 / CRLF wih require-starting-space.

setup.cfg
Avoid W503/W504 with current code as the current code not compliant
and they are contradictory.
=> Added flake8 ignores

docs/conf.py
There was a change in behavior of E402, see:
https://gitlab.com/pycqa/flake8/-/issues/638#note_345108633
=> style: Fix 'noqa' for flake8 3.8.0

docs/configuration.rst, tests/rules/test_key_ordering.py, tests/test_cli.py, yamllint/cli.py, yamllint/config.py, yamllint/rules/key_ordering.py
Support sorting by locale with strcoll(). Properly handle case and accents.
=> Add "locale" config to key-ordering rule

docs/configuration.rst, tests/rules/test_key_ordering.py, tests/test_cli.py, yamllint/cli.py, yamllint/config.py, yamllint/rules/key_ordering.py
Compared to the PR before, this does not set a default locale at all. If the `locale` config option is not used, no `setlocale()` is executed, so no error possible.
=> Key ordering with locale, take #2

.travis.yml, tests/common.py, tests/test_cli.py
Preventing regressions like #285
=> Add build environment without UTF-8 locales to travis-ci

yamllint/rules/braces.py, yamllint/rules/brackets.py, yamllint/rules/colons.py, yamllint/rules/commas.py, yamllint/rules/comments.py, yamllint/rules/document_end.py, yamllint/rules/document_start.py, yamllint/rules/empty_lines.py, yamllint/rules/empty_values.py, yamllint/rules/hyphens.py, yamllint/rules/indentation.py, yamllint/rules/line_length.py, yamllint/rules/new_lines.py, yamllint/rules/octal_values.py, yamllint/rules/quoted_strings.py, yamllint/rules/truthy.py
This adds default values to the documentation for all rules with options. The YAML blocks should themselves follow the defaults with indentation, spacing and quoting.
The `octal-values` rule did not have its options listed; they have been added.
This uses `.. code-block:: yaml` for the code blocks, which results in YAML syntax highlighting the same as on the Configuration page, but different from the example code snippets on the rules page, which use just `::`, resulting in default highlighting. Let me know what is preferred.
Closes #290
=> docs: Add default values to rules with options

docs/configuration.rst
Related to https://github.com/adrienverge/yamllint/issues/311.
=> docs: Make 'yaml-file' config documentation clearer

tests/rules/test_braces.py, tests/rules/test_brackets.py, yamllint/rules/braces.py, yamllint/rules/brackets.py
This is another try to accomplish the same thing in the PR #314 without adding new rules.
It's desirable for some use cases such like ansible playbooks to forbid flow collection styles as needed and this changs make that happen.
Of course, these should not be enabled for most use cases so that these configurations are disable by default.
=> Add 'forbid' configuration parameters to the braces and brackets rules

setup.cfg
Because yamllint depends on pkg_resources.load_entry_point from
setuptools to make it worked, this runtime dependency to setuptools is
necessary to list.
=> fix: add runtime dependency to setuptools

docs/integration.rst, tests/test_cli.py, yamllint/cli.py
This adds support for the output format that GitHub Actions can use to automatically annotate pull requests with linter failures.
I'm not very good with Python, so there are two ugly things I need recommendations for improving:
1. The two tests define the same magical output twice. I image I could go to one variable outside of the function definition, but I don't know where to put it
2. In the test for auto-detection I don't think the way I unset variables is as clean as it could be
I tested this by adding a bad YAML file (`a.yaml`) and then creating a GitHub Actions definition in `.github/workflows/test.yml` that looks like this
```yaml
---
name: yamllint test
on: push
jobs:
test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Set up Python
uses: …
```
=> Add support for GitHub annotations

tests/test_yamllint_directives.py, yamllint/linter.py
Fixes #325 
The linter allows a directive to contain trailing whitespace characters like `\r`, but does not trim them before iterating on the rules. As a result, the last rule in the list contains the trailing whitespace characters and never matches any existing rule.
I added the necessary trimming, as well as a test with 2 checks to go along with it.
=> directives: Fix DOS lines messing with rule IDs

.gitignore
Quick PR to ignore the `/.eggs` folder, which appears to be generated every time the `python setup.py test` command is run.
=> gitignore: Add /.eggs

.travis.yml, CONTRIBUTING.rst
Using `python setup.py test` is now deprecated [1], users are encouraged
to be explicit about the test command.
Running yamllint tests using the Python standard library (`unittest`)
can be done using:
python -m unittest discover
Why not nose, tox or pytest? Because they would add a dependency, make
tests running more complicated and verbose for new users, and their
benefit is not worth for this simple project (only 2 runtime
dependencies: PyYAML and pathspec).
Resolves https://github.com/adrienverge/yamllint/issues/328.
\[1]: https://github.com/pypa/setuptools/pull/1878
=> tests: Stop using deprecated 'python setup.py test'

tests/test_cli.py, tests/test_config.py, tests/test_module.py
Rebasing of PR #330. This replaces the `unittest` deprecated aliases to avoid warnings when running the tests.
For more info: https://docs.python.org/3/library/unittest.html#deprecated-aliases
=> tests: Replace deprecated aliases

.travis.yml, setup.cfg
Add support for Python 3.9 since it was officially released in October and drop support for Python 3.4 since it is end-of-life (EOL).
Also, tried testing yamllint on Python 3.4 and it seems `pyyaml` has dropped support for Python 3.4, so another good reason to drop:
```
❯ sudo /usr/local/bin/python3.4 -m pip install pyyaml                                                                                                      (base)
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting pyyaml
Downloading https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz (269kB) …
```
=> Add support for Python 3.9, drop Python 3.4

tests/rules/test_braces.py, tests/rules/test_brackets.py, yamllint/rules/braces.py, yamllint/rules/brackets.py
We'd like to disallow brackets and braces in our YAML, but there's a
catch: the only way to describe an empty array or hash in YAML is to
supply an empty one (`[]` or `{}`). Otherwise, the value will be null.
This commit adds a `non-empty` option to `forbid` for brackets and
braces. When it is set, all flow and sequence mappings will cause errors
_except_ for empty ones.
=> Allow only non-empty brackets/braces

.travis.yml, README.rst, setup.cfg, tests/rules/test_line_length.py, tests/test_cli.py, tests/test_config.py, tests/test_module.py, yamllint/linter.py, yamllint/rules/line_length.py
As planned and advertized, yamllint drops support for Python 2 on 2021.
=> End support for Python 2

tests/rules/test_quoted_strings.py, yamllint/rules/quoted_strings.py
PyYAML implements YAML spec version 1.1, not 1.2. Hence, values starting
with `0o` are not considered as numbers: they are just strings, so they
need quotes when `quoted-strings: {required: true}`.
```python
>>> import yaml
>>> yaml.resolver.Resolver().resolve(yaml.nodes.ScalarNode, '100', (True, False))
'tag:yaml.org,2002:int'
>>> yaml.resolver.Resolver().resolve(yaml.nodes.ScalarNode, '0100', (True, False))
'tag:yaml.org,2002:int'
>>> yaml.resolver.Resolver().resolve(yaml.nodes.ScalarNode, '0o100', (True, False))
'tag:yaml.org,2002:str'
```
Let's try to prevent that.
Fixes https://github.com/adrienverge/yamllint/issues/351.
=> quoted-strings: Fix explicit octal recognition

setup.cfg
> In recent versions of setuptools and Python, console-script entry
points are using stdlib importlib by default, thus setuptools is no
longer a runtime dependency.
pypa/setuptools#2197
https://github.com/pypa/setuptools/blob/main/CHANGES.rst#v4730
https://docs.python.org/3/library/importlib.metadata.html
=> setuptools is a runtime dep only for Python < 3.8

.github/workflows/ci.yaml
Very probably due to:
https://github.com/actions/virtual-environments/issues/2455#issuecomment-787511010
---
=> CI: Fix failing 'coverage' command because of $PATH

tests/rules/test_line_length.py, yamllint/rules/line_length.py
Whenever a comment start with more than 1 `#` then using the following config
```yaml
rules:
line-length:
max: 20
allow-non-breakable-words: true
```
to lint the following document:
```yaml
key:
subkey: "value"
```
will disregard the `max` property and issue an error/warning anyway.
This PR addresses that by jumping not 2 but `length_of_hash_signs_at_line_begining + 1`
=> line_length: skip all hash signs starting comment

setup.cfg
According to [PEP 345 Requires-Python](https://www.python.org/dev/peps/pep-0345/#requires-python), the value of this field must be a valid [Version Specifier](https://www.python.org/dev/peps/pep-0345/#version-specifiers). Which in turn expects this to comply with [PEP 440](https://www.python.org/dev/peps/pep-0440/).
While not an issue for those that directly use `pip`, this will cause issues for `poetry` users in the next release (if their current stance is maintained). Discussion of the issue and there stance can be found here: https://github.com/python-poetry/poetry/issues/4095.
resolves #387
=> setup: update python_requires to comply with PEP 345/440

setup.cfg
This reverts commit 8f68248 "Remove runtime dep 'setuptools' for Python
< 3.8". It looks like removing setuptools induces problems on some
systems, see for example the linked discussion.
Fixes https://github.com/adrienverge/yamllint/issues/380.
=> Restore setuptools requirement for Python < 3.8

.github/workflows/ci.yaml, setup.cfg
- Add support for Python 3.10 released on 2021-10-04
- Drop support for Python 3.5 since it has reached end-of-life
- Fix github actions workflow:
- install correct Python version
- run tests after linting
- add ~/.local/bin to system path for both jobs
=> Add support for Python 3.10, drop Python 3.5

yamllint/cli.py
Moved the auto arg_format selection out of the main if block into a separate logic section to improve readability.
No logic changes.
=> separate auto args_format logic

tests/test_cli.py, yamllint/cli.py
Resolves #421
Update the github formatting to utilize groups in the output and provide the line/column number for the error in the output log.
=> Update github formatting output to utilize groups

tests/rules/test_comments.py, yamllint/rules/comments.py
Basically, any character is now allowed after the shebang marker.
=> fix: allow whitespace after the shebang marker. Closes #428.

docs/integration.rst
This PR corrects the link syntax for a reference on integration.rst.
=> Correct link syntax on integration.rst

docs/configuration.rst
I attempted to make the docs more understandable for those who are unfamiliar with files that start with `.` or don't have a file extension in the name.
Closes #96, Closes #212
=> Attempt to clarify configuration file location

tests/rules/test_key_duplicates.py, yamllint/rules/key_duplicates.py
If there's nothing to do when the stack is empty then this should fix issue #452 as can be seen below : 
```shell
$ git clone https://github.com/yaml/yaml-test-suite
$ cd yaml-test-suite
$ make data-update
$ yamllint data/4H7K/in.yaml
data/4H7K/in.yaml
2:2       error    too many spaces inside brackets  (brackets)
2:10      error    too many spaces inside brackets  (brackets)
2:12      error    too many spaces inside brackets  (brackets)
2:13      error    syntax error: expected '<document start>', but found ']' (syntax)
$ 
```
=> Don't break on empty stack

.github/workflows/ci.yaml, README.rst
This tool was helpful in catching style issues I made as I was writing #463. It adds approximately 2 seconds to the lint action run time.
The only complaint it had on existing documentation was petty (`Duplicate explicit target name: "read more in the complete documentation!".` - see https://github.com/sphinx-doc/sphinx/issues/3921), but I changed it anyway.
=> Add rstcheck to CI to lint docs

tests/common.py, tests/rules/test_key_ordering.py, tests/rules/test_octal_values.py, tests/test_cli.py, tests/test_config.py, tests/test_linter.py
- Add a `temp_workspace` context manager to simplify writing new tests.
- Add `# pragma: no cover` to unit test code paths used for skipping tests.
These code paths are only covered when tests are skipped.
That makes it impractical to reach full code coverage on the unit test code.
Having full coverage of unit tests is helpful for identifying unused tests.
- Test the `octal-values` rule with a custom tag.
- Test the cli `-d` option with the `default` config.
- Test support for the `XDG_CONFIG_HOME` env var.
- Test warning message output.
- Test support for `.yamllint.yml` config files.
- Test support for `.yamllint.yaml` config files.
- Test error handling of a rule with a non-enable|disable|dict value.
- Test error handling of `ignore` with a non-pattern value.
- Test error handling of a …
=> tests: Increase test coverage

yamllint/linter.py
Remove two `try/except UnicodeError` exception handlers which were added in commit c8ba8f7e99ad00ba84c65cd49e2cd288388cc232 for Python 2.x compatibility. Now that Python 2.x is no longer supported, the `except` is unreachable and is no longer needed.
=> linter: Remove unreachable exception handler

yamllint/linter.py
Remove the redundant conditional used when reporting a syntax error at the same location as a cosmetic problem. Also reword the comment explaining the logic to more accurately describe the situation.
This eliminates an unreachable `syntax_error = None` assignment.
=> linter: Remove redundant conditional

yamllint/rules/octal_values.py
This change introduces a fairly simple performance improvement; it statically compiles the `_is_octal_number_regex` rather than compiling it each time the checker is called.
=> octal values: pre-compile octal regex

tests/rules/test_new_lines.py, yamllint/rules/new_lines.py
This PR follows up on #456 in which it was concluded that the default for the new-lines rule should not be changed but rather a new option is to be introduced.
As explained in [this comment on the parent PR](https://github.com/adrienverge/yamllint/pull/456#issuecomment-1119438897) yamllint currently has portability issues that make it hard to use on Windows clients. These stem from git converting line-endings to the platform default on checkout and yamllint assuming that the line-ending type should be enforced for all development platforms. This leads to windows-clients needing to be heavily reconfigured to make yamllint work there properly.
This PR introduces a new option for the `new-lines` rule: `type: auto`.
The new option infers the correct newline character(s) from the operating …
=> rule new-lines: add `type: platform` configuration option

docs/conf.py, yamllint/__init__.py
Brought up in #476. I ran `make html man` and then inspected the copyright text and it looks good to me. Bumped the year so it shows that stuff still happens here 😁
=> Remove word 'copyright', bump year

docs/integration.rst, docs/text_editors.rst
My original example had too much extra stuff that changes over time. A user can rely upon whatever version of Python `ubuntu-latest` has to be a reasonable choice that yamllint supports.
=> Simplify GitHub actions example

tests/rules/test_quoted_strings.py, yamllint/rules/quoted_strings.py
This PR implements ~~`skip-quoted-quote`~~ `allow-quoted-quotes` option that allows strings like:
- `'foo"bar'` on `quote-type: double`
- `"foo'bar"` on `quote-type: single`
Closes use-case with quotes inside the string from #424. But still no solution for escape sequences.
=> quoted-strings: add allow-quoted-quotes option

yamllint/rules/quoted_strings.py
=> quoted-strings: fix docs example

.github/workflows/ci.yaml, setup.cfg
https://peps.python.org/pep-0494/
=> ci: Python 3.6 reached end-of-life on 2021-12-23

tests/rules/test_float_values.py, yamllint/rules/float_values.py
The rule correctly reports number values like `.1`, `1e2`, `.NaN` and `.Inf`, but it also reported false positives on strings like `.1two3`, `1e2a`, `.NaNa` and `.Infinit∞`.
The regexps need to end with an end delimiter (`$`) otherwise longer strings can be matched too.
Fixes https://github.com/adrienverge/yamllint/issues/495
---
@DerekTBrown @nyuszika7h for info
=> float-values: Fix bug on strings containing fordidden values

setup.cfg
This reverts commit 3c525ab "Release as a universal wheel".
Python 2 support was definitely dropped in early 2021 in commit a3fc64d, since then it's no longer useful to build universal wheels.
According to the `wheel` documentation:
> If your project contains no C extensions and is expected to work on
> both Python 2 and 3, you will want to tell wheel to produce universal
> wheels
Partly fixes https://github.com/adrienverge/yamllint/issues/501
=> build: Stop releasing universal wheels

tests/rules/test_indentation.py, yamllint/rules/indentation.py
Currently, when spaces: consistent, and indent-sequences: true (the defaults), the expected indent for an unindented block sequence is arbitrarily set to 2 expecting it to be at the start of the document. Unfortunately, this causes a bug when the expected indent should be more than 2. For example, in nested collections like the one below, linting would pass, even though the expected indent is _at least_ 3  (since spaces: consistent doesn't enforce how many spaces should be used for indentation). I first reported this behavior in issue #485, which this PR resolves. 
```yaml
---
- item:
- elem 1
- elem 2 
```
Instead of setting the expected indent value to 2 arbitrarily, this change sets the value to -1, to explicitly indicate that indentation is required, but the expected indent value is …
=> fix: ensure indent-seq works in nested collections

tests/rules/test_indentation.py
Commit 764586d "indentation: Fix indent-sequences in nested collections" introduced 2 style-related problems:
tests/rules/test_indentation.py:1394:45: E231 missing whitespace after ','
tests/rules/test_indentation.py:1402:45: E231 missing whitespace after ','
Let's fix them.
=> style: Fix indentation test file missing whitespace

docs/disable_with_comments.rst
We get a lot of duplicate issues about this. I added a workaround similar to the one I mentioned in responding to #462 that I have used.
=> Clarify 'disable-line' and parser errors

.github/workflows/ci.yaml, docs/disable_with_comments.rst
This problem was just introduced by commit cec4f33 "Clarify disable-line
and parser errors, workaround" and produced this error when building
documentation:
docs/disable_with_comments.rst:120:Could not lex literal_block as
"yaml". Highlighting skipped.
---
Recently `python setup.py build_sphinx` started failing with:
pkg_resources.VersionConflict: (Pygments 2.3.1
(/usr/lib/python3/dist-packages), Requirement.parse('Pygments>=2.12'))
The reason is that `doc8` 1.0.0 installs `Pygments` 2.3.1, then `Sphinx`
5.3.0 needs `Pygments` ≥ 2.12.
The easiest fix is to change the install order.
=> CI: Fix Sphinx-related errors on 'linter' step

docs/conf.py, tests/test_cli.py, tests/test_linter.py, yamllint/__init__.py, yamllint/rules/quoted_strings.py
No need for `u'€'`, just use `'€'`.
=> All strings are Unicode in Python 3

tests/test_spec_examples.py, yamllint/cli.py, yamllint/parser.py, yamllint/rules/indentation.py
* `io.open()` is an alias for for the builtin `open()` function:
https://docs.python.org/3/library/io.html#io.open
* If `open()` cannot open a file, an `OSError` is raised:
https://docs.python.org/3/library/functions.html#open
* `EnvironmentError` is kept for compatibility with previous versions; starting from Python 3.3, it is an alias of `OSError`:
https://docs.python.org/3/library/exceptions.html#EnvironmentError
* Directly yield from an iterable instead of iterating to yield items.
=> Apply some pyupgrade suggestions

docs/configuration.rst, tests/test_config.py, yamllint/config.py
This may feel more natural for some users, rather than embedding multiple entries in a multi-line string.
=> Allow using a list of strings in ignore configuration

docs/configuration.rst, tests/test_cli.py, yamllint/cli.py
This PR adds the command line option `--list-files` which list files to lint and exits.
This is useful to determine which files are being linted to check configuration changes like `yaml-files` and `ignore` more conveniently.
```
$ yamllint -h
usage: yamllint [-h] [-] [-c CONFIG_FILE | -d CONFIG_DATA] [-f {parsable,standard,colored,github,auto}] [-s]
[--no-warnings] [-v]
[FILE_OR_DIR ...]
A linter for YAML files. yamllint does not only check for syntax validity, but for weirdnesses like key
repetition and cosmetic problems such as lines length, trailing spaces, indentation, etc.
positional arguments:
FILE_OR_DIR           files to check
optional arguments:
-h, --help            show this help message and exit
-                     read from standard input
-c CONFIG_FILE, --config-file …
```
=> feat: Add --list-files command line option

docs/development.rst
`yamllint.linter.run("example.yaml", yaml_config)` example seems `yamllint.linter.run` opens a given file.
It's misleading.
=> Fix misleading Python API example

docs/disable_with_comments.rst
rstcheck succeeds with a failure (heh) when there's a code block without a language specified. This can lead to false negatives as the file is no longer being checked by rstcheck.
Error:
An `AttributeError` error occured. This is most propably due to a
code block directive (code/code-block/sourcecode) without a
specified language. This may result in a false negative for source:
'docs/disable_with_comments.rst'. See
https://rstcheck-core.readthedocs.io/en/latest/faq/#code-blocks-without-language-sphinx
for more information.  Success! No issues detected.
=> docs: Explicitly specify language even when it's plain text

yamllint/linter.py
As reported in https://github.com/adrienverge/yamllint/pull/548, there might be a problem with pathspec 0.11.1 which does't allow calling `match_file()` with argument `None` anymore.
The `linter.run()` function shouldn't call `YamlLintConfig.is_file_ignored(None)` anyway.
=> linter: Prevent testing is_file_ignored() with filepath == None

docs/rules.rst, tests/rules/test_anchors.py, yamllint/conf/default.yaml, yamllint/rules/__init__.py, yamllint/rules/anchors.py
According to the YAML specification [^1]:
- > It is an error for an alias node to use an anchor that does not
> previously occur in the document.
The `forbid-undeclared-aliases` option checks that aliases do have a matching anchor declared previously in the document. Since this is required by the YAML spec, this option is enabled by default.
- > The alias refers to the most recent preceding node having the same
> anchor.
This means that having a same anchor repeated in a document is allowed. However users could want to avoid this, so the new option `forbid-duplicated-anchors` allows that. It's disabled by default.
- > It is not an error to specify an anchor that is not used by any
> alias node.
This means that it's OK to declare anchors but don't have any alias referencing them. However …
=> anchors: Add new rule to detect undeclared or duplicated anchors

tests/rules/test_anchors.py, tests/rules/test_colons.py, yamllint/rules/colons.py
Although accepted by PyYAML, `{*x: 4}` is not valid YAML: it should be
noted `{*x : 4}`. The reason is that a colon can be part of an anchor
name. See this comment from Tina Müller for more details:
https://github.com/adrienverge/yamllint/pull/550#discussion_r1155297373
Even if it's not a problem for yamllint, let's fix our tests to include
valid YAML snippets.
---
In the rare case when the key before `:` is an alias (e.g. `{*x : 4}`),
the space before `:` is required (although this requirement is not
enforced by PyYAML), the reason being that a colon can be part of an
anchor name. Consequently, this commit adapts the `colons` rule to avoid
failures when this happens.
See this comment from Tina Müller for more details:
https://github.com/adrienverge/yamllint/pull/550#discussion_r1155297373 …
=> Adapt 'anchors' and 'colons' for the required space after an alias key

README.rst
It is a leftover from commit 66bf76a "CI: Switch to GitHub Actions".
=> README: Update CI status badge

.github/workflows/ci.yaml, docs/Makefile, setup.cfg
Because `setup.py` is deprecated, let's switch from:
python setup.py build_sphinx
to:
make -C docs html
to build Sphinx documentation.
The generated HTML files in `docs/_build/html` are exactly the same (I compared with `diff -qr`).
Also add `-W` (turn warnings into errors) to the `sphinx-build` options to keep the previous behavior.
=> build: Stop using setup.py to generate documentation

tests/rules/test_anchors.py, yamllint/rules/anchors.py
This change implements one of the options discussed in #395 . A new option for `anchors` rule named `forbid-unused-anchors`. If the option is enabled, yamllint will report about anchors that has been declared but is not used. The option is disabled by default as yaml specs doesn't require anchors to be used.
Rest of the options for this rule is being implemented by #420.
=> feat: add rule for unused anchors

yamllint/rules/anchors.py
Existing `anchors` options use quotes around the anchor name:
2:3       error    found undeclared alias "unknown"  (anchors)
4:3       error    found duplicated anchor "dup"  (anchors)
Let's do the same in the newly-added option `forbid-unused-anchors`:
5:3       error    found unused anchor "not used"  (anchors)
---
Like the rest of the project does.
=> anchors: Add missing quotes in unused anchor error message

docs/configuration.rst, tests/test_cli.py, yamllint/cli.py
Inspired be ESLint's search, it looks for configuration files in all parent directories up until it reaches the user's home or root.
closes #571
=> Look for per-project configuration file in parent directories

tests/rules/test_document_end.py, yamllint/rules/document_end.py
Fixes #560 when DocumentStartToken is preceded by `DirectiveToken`.
=> document-end: Fix spurious "missing document end"

tests/test_cli.py
* Simplify [super()](https://docs.python.org/3/library/functions.html#super)
https://github.com/asottile/pyupgrade#super-calls
* UTF-8 is the default for [encode()](https://docs.python.org/3/library/stdtypes.html?highlight=encode#str.encode)
https://github.com/asottile/pyupgrade#encodeutf-8
=> tests: Apply pyupgrade suggestions

tests/test_cli.py, tests/test_spec_examples.py, yamllint/cli.py, yamllint/config.py, yamllint/linter.py, yamllint/rules/__init__.py, yamllint/rules/empty_lines.py, yamllint/rules/indentation.py, yamllint/rules/key_duplicates.py, yamllint/rules/key_ordering.py, yamllint/rules/octal_values.py, yamllint/rules/quoted_strings.py
=> style: Use f-strings wherever possible

.github/workflows/ci.yaml
~~Python 3.12 release candidates are available, and version 3.12 has been available in GitHub runners for almost a year:
https://github.com/actions/setup-python/issues/514~~
=> CI: Add support for Python 3.12

tests/rules/test_empty_values.py, yamllint/rules/empty_values.py
feat: Add `forbid-in-list-items` feature to detect empty values in lists
This commit introduces a new feature, `forbid-in-list-items`, which allows users to check for empty values within lists. The default behavior is set to `false`, but it can be activated by setting the `forbid-in-list-items` configuration variable to `true`.
The `check` function has been updated to handle this feature, and it will now identify and report empty values within list items when `forbid-in-list-items` is enabled.
This enhancement provides users with more control and flexibility when using the linter for YAML files.
=> Add forbid-in-block-sequences feature for detecting empty values in block sequences

docs/disable_with_comments.rst
Some YAML snippets from the examples were actually invalid.
=> docs: Fix new rstcheck errors

tests/test_config.py, yamllint/config.py
Fix #542. The `ignore-from-file` key wasn't validated in `validate_rule_conf`.
=> fix (#542): validate `ignore-from-file` in `validate_rule_conf`

.readthedocs.yaml
As explained on https://readthedocs.org/projects/yamllint/:
> Your builds will stop working soon!
> Configuration files will soon be required by projects, and will no
> longer be optional. Read our blog post to create one and ensure your
> project continues building successfully.
https://blog.readthedocs.com/migrate-configuration-v2/
=> build: Migrate to use .readthedocs.yaml for docs generation

tests/rules/test_quoted_strings.py, yamllint/rules/quoted_strings.py
Flow maps and sequences need quotes if the values contain any of the flow tokens ({}, [], ','). However, yamllint generates false positives in these cases:
$ yamllint -d 'rules: {quoted-strings: {required: only-when-needed}}' - <<<'field: ["string[bracket]"]'
1:9       error    string value is redundantly quoted with any quotes  (quoted-strings)
To fix this, track when inside a flow map/sequence and skip the quoting checks except for the quoting type.
Closes #516
=> Fix quoted-strings checks in flow maps and sequences

tests/rules/test_quoted_strings.py, yamllint/rules/quoted_strings.py
=> Add `check-keys` option to `quoted-strings` rule

tests/test_cli.py
Yamllint dropped support for Python 3.6 in september 2022.
=> tests: Remove test skipping for Python < 3.7

tests/test_cli.py
Before this change, if certain tests were failing in certain ways, then running `python -m unittest --buffer` would cause an `AttributeError` in the `unittest` module itself.
Here’s what `unittest` does when you use the `--buffer` argument:
1. [It sets `sys.stdout` and `sys.stderr` to `StringIO`s][1].
2. It runs a test.
3. [If the test failed, it runs `getvalue()` on `sys.stdout` and `sys.stderr` to get data from its `StringIO`s][2].
`tests/test_cli.py` has its own `RunContext` class that does something similar. Before this change, here’s what could happen:
1. `unittest` sets `sys.stdout` and `sys.stderr` to `StringIO`s.
2. `unittest` runs a test that uses `RunContext`.
3. A `RunContext` gets entered. It sets `sys.stdout` and `sys.stderr` to its own `StringIO`s.
4. The `RunContext` gets …
=> tests: Prevent `unittest --buffer` from crashing

tests/test_cli.py
See the individual commits for details.
While I was working on implementing what was discussed [here](https://github.com/adrienverge/yamllint/issues/621#issuecomment-1872579265), I realized that there were other edge cases where environment variables could cause problems. For example, running `YAMLLINT_CONFIG_FILE=/random/binary/file python -m pytest discover` caused a bunch of new test failures. I decided to implement a more robust solution that fixes the problem for more than just `test_run_with_user_global_config_file`.
Fixes #605. Fixes #621.
=> Environment variable-related test fixes

yamllint/cli.py
See #600 / f63e56f.
- The format() call was missing in the first place for `filename`.
- Other format() calls are obviously useless now that f-strings perform string interpolation.
=> cli: remove format() left over in f63e56f

tests/common.py, yamllint/config.py
Fixes the only error reported by [ruff](https://astral.sh/ruff) using default settings:
```
E721 Do not compare types, use `isinstance()`
```
=> style: apply ruff suggestion

docs/integration.rst
Perhaps better to add this example to the docs rather than it getting lost in a issue comment https://github.com/adrienverge/yamllint/issues/243#issuecomment-1879181516
=> docs: add GitLab CI / Code Climate example

yamllint/__main__.py
```
CPY001 Missing copyright notice at top of file
```
Do not apply this rule to empty files:
* `tests/rules/__init__.py`
and to files generated by tools:
* `docs/conf.py`
=> style: apply flake8-copyright rules

.flake8, .github/workflows/ci.yaml, .ruff.toml, CONTRIBUTING.rst, pyproject.toml, tests/rules/test_indentation.py, tests/test_spec_examples.py
* Start with reverting parts of commit 26be794 in #629 related to config and CI jobs.
* Undo ruff changes that conflict with flake8
Fixes https://github.com/adrienverge/yamllint/issues/628#issuecomment-1920820663.
=> Revert replacement of flake8 with ruff

tests/rules/test_truthy.py, yamllint/rules/truthy.py
Specification of YAML ≤ 1.1 has 22 boolean values:
y     | Y            | n     | N
yes   | Yes   | YES  | no    | No    | NO
true  | True  | TRUE | false | False | FALSE
on    | On    | ON   | off   | Off   | OFF
Whereas YAML 1.2 spec recognizes only 6 [^1]:
true  | True  | TRUE | false | False | FALSE
For documents that explicit state their YAML spec version at the top of the document, let's adapt the list of forbidden values.
In the future, we should:
- implement a configuration option to declare the default YAML spec version, e.g. `default-yaml-spec-version: 1.2`,
- consider making 1.2 the default in a future release (this would be a slight breaking change, but yamllint always tried to be 1.2-compatible).
- consider adapting yamllint to other 1.1 vs. 1.2 differences [^2].
Solves: …
=> truthy: Adapt forbidden values based on YAML version

.github/workflows/ci.yaml, .readthedocs.yaml, docs/conf.py, docs/requirements.txt
https://yamllint.readthedocs.io/en/v1.34.0/ was rendered differently than previous versions, very probably due to change of commit ca7f8b9 "Migrate to use .readthedocs.yaml for docs generation".
Let's restore the `sphinx_rtd_theme` theme.
=> build: Restore official Read the Docs theme

tests/common.py, tests/test_cli.py, tests/test_config.py, yamllint/cli.py, yamllint/linter.py
Before this commit, yamllint would output "[Errno 2] No such file or directory" when running on a directory which contained a broken symbolic link, even if the file is set to be ignored in yamllint configuration.
This commit fixes that, and adds corresponding tests.
As a side effect this changes `yamllint.linter.run(stream, config)`, so tools that would use this API need to filter ignored files beforehand.
Fixes https://github.com/adrienverge/yamllint/issues/399
=> cli: Cleanly skip broken symlinks that are ignored

tests/test_cli.py, tests/test_config.py, yamllint/cli.py, yamllint/linter.py
Commit 2344380 "Cleanly skip broken symlinks that are ignored" fixed a problem on symbolic links but also introduced a change on how ignored files should be treated, depending on whether they're explicitely passed as command-line arguments or not [^1].
This change is annoying for users that dynamically build the list of files to pass as arguments, e.g. [^2]:
find -name '*\.yaml' | xargs yamllint
The present commit adds unit tests for `yamllint [FILES]...` and `yamllint --list-files [FILES]...`, that passed with previous version 1.34.0, and restore the behavior of this version.
As a result it also reverts the API change of commit 2344380 on `yamllint.linter.run(stream, config)`.
[^1]: https://github.com/adrienverge/yamllint/issues/657#issuecomment-1948009315
[^2]: …
=> cli: Restore ignoration of files passed as command-line arguments

docs/development.rst
Since yamllint version 0.5.2 (in 2016, just after yamllint was created) this example in documentation doesn't work. Indeed, commit dbbecb5 (which aimed to solve another problem) removed the ability to import yamllint submodules directly.
This commit makes it clearer inside documentation.
Fixes https://github.com/adrienverge/yamllint/issues/698
=> docs: Import 'yamllint.config' rather than 'yamllint'

.github/workflows/ci.yaml
And drop support for Python 3.8 (end-of-life since 2024-10-07).
=> CI: Add support for Python 3.13

tests/test_cli.py
This is a simple preparation for the next commit, to get rid of
low-level `fcntl.fcntl()` calls, since `os.set_blocking()` now exists
(since Python 3.5).
---
Since I don't have Python 3.14 on my system (yet), here are the steps I
used to reproduce:
sudo dnf install python3.14
python3.14 -m venv /tmp/py3.14
source /tmp/py3.14/bin/activate
pip install yaml pathspec
python3.14 -m unittest discover
python3.14 -m unittest tests.test_cli.CommandLineTestCase.test_run_default_format_output_in_tty
This commit fixes that by piping *only* `sys.stdout`, not `sys.stderr`
too. I'm not sure why I wrote this code in 2016 (see commit a2c68fdf),
but the new one makes more sense to me now.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2336947
=> cli: Fix TTY test failing on Python 3.14

tests/rules/test_key_ordering.py, yamllint/rules/key_ordering.py
This change allows ignoring certain keys by filling the `ignored-keys` option with a list of PCRE regexes to select strings to ignore.
---
Note: this is a follow up of the pull request at https://github.com/adrienverge/yamllint/pull/689, see why [on this comment](https://github.com/adrienverge/yamllint/pull/689#issuecomment-2701603867).
=> key-ordering: Add ignored-keys option

tests/rules/test_quoted_strings.py, yamllint/rules/quoted_strings.py
- Add test case to reproduce #700 
- When checking whether quotes are needed, assume that double-quoted strings containing special characters have already been escaped (and claim the quotes are in fact needed)
=> fix: allow backslash-escaped special characters in double-quoted strings (#700)

MANIFEST.in
This commit fixes a problem reported by Nicholas Bollweg at https://github.com/adrienverge/yamllint/pull/725. Recent commit a3e1325 "CI: Publish PyPI releases using GitHub Actions workflows" and automatic publication of version 1.36.1 revealed a problem that had probably been there for some time: most documentation and test files weren't included in the source distribution when running `python -m build` (unless an `yamllint.egg-info` from a previous run listed them).
I see two solutions:
1. Add plugin `setuptools-scm` in `pyproject.toml`:
```toml
requires = ["setuptools >= 61", "setuptools-scm >= 8"]
```
This would add all files tracked by Git in the sdist, including a few that aren't really needed: `.flake8`, `.github`, `.readthedocs.yaml`…
2. Declare extra files to embed in …
=> build: Restore documentation and test files in sdist

.github/workflows/publish.yaml
This commit prevents the failure of the GitHub Actions job "Publish distribution package to TestPyPI" on most pushes (see discussion at https://github.com/adrienverge/yamllint/issues/721#issuecomment-2727167030), since recent commit a3e1325 "CI: Publish PyPI releases using GitHub Actions workflows".
Indeed, TestPyPI doesn't allow repushing the same version. Use `skip-existing` to prevent to such failures on the CI.
An alternative would be to use the `setuptools-scm` plugin to define a unique version for each commit (e.g. `1.36.2.dev2+gd4f1c14`), but it requires more changes (define the version in `pyproject.toml`, fetch tags from GitHub in `publish.yaml`, exclude `.*` + `.github/**` files in `MANIFEST.in`). Moreover it doesn't work as is: to prevent errors like `HTTP 400 The use of local …
=> CI: Ignore version duplicates when publishing to TestPyPI

.github/workflows/publish.yaml
This follows commit 7d52df7 "CI: Ignore version duplicates when publishing to TestPyPI" with a better design:
- Only publish builds from `master` branch on TestPyPI.
- Version every non-tag commit with a `.devN` suffix, e.g. `1.36.2.dev1`. This prevents duplicates on TestPyPI.
- `twine check` built packages.
See discussion at
https://github.com/adrienverge/yamllint/issues/721#issuecomment-2731027692 for more details.
=> CI: Publish each master commit with a unique version on TestPyPI

.github/workflows/tests.yaml, docs/character_encoding.rst, docs/configuration.rst, docs/index.rst, tests/__init__.py, tests/common.py, tests/test_cli.py, tests/test_config.py, tests/test_decoder.py, tests/test_module.py, yamllint/cli.py, yamllint/config.py, yamllint/decoder.py, yamllint/linter.py
This PR makes sure that yamllint never uses `open()`’s default encoding. Specifically, it uses the character encoding detection algorithm specified in [chapter 5.2 of the YAML spec](https://yaml.org/spec/1.2.2/#52-character-encodings) when reading both YAML files and files that are on [the `ignore-from-file` list](https://yamllint.readthedocs.io/en/stable/configuration.html#ignoring-paths).
There are [two](https://github.com/adrienverge/yamllint/pull/240) [other](https://github.com/adrienverge/yamllint/pull/581) PRs that are similar to this one. Here’s how this PR compares to those two:
- This PR doesn’t have any merge conflicts.
- This PR has a cleaner commit history. You can run the tests and flake8 on each commit in this PR, and they’ll report no errors. I don’t think that you can do …
=> Automatically detect character encoding of YAML files and ignore files

.github/workflows/publish.yaml
This fixes a problem in the custom versions `v1.37.0.devN` built for publishing on TestPyPI since commit 325fafa "Publish each master commit with a unique version on TestPyPI".
Such versions are constructed by suffixing `.devN`, where `N` is the number of commits since last tags. In the `N = 0` case, we need to add `--long` to `git describe --tags`. Otherwise it yields `v1.37.0` instead of `v1.37.0-0-gbe92e15`, and the CI fails, e.g. on https://github.com/adrienverge/yamllint/actions/runs/14017589005/job/39245225221
packaging.version.InvalidVersion: Invalid version: '1.37.0.devv1.37.0'
=> CI: Fix TestPyPI "dev0" versions for master commits on tags

yamllint/rules/comments.py
When telling someone that there are too few spaces before a comment it can be useful to include how many were expected.
=> Give context about how many spaces were expected

README.rst
Updated the link to the test ci status, according to the changes made in commit 1c3bbb2.
=> Fix the badge link in `README.md`

tests/rules/test_quoted_strings.py, yamllint/rules/quoted_strings.py
On double-quoted multiline strings, quotes aren't needed if lines are broken on spaces, e.g.:
multiline:
"this is a sentence
cut into words"
But quotes are needed when at least one line ends with a backslash character (`\`), meaning that the next spaces should be removed:
multiline:
"https://example.com/a/very/very\
/very/very/long/URL"
This commit fixes that.
Fixes https://github.com/adrienverge/yamllint/issues/275
=> quoted-strings: Fix only-when-needed on multiline with backslash

docs/integration.rst
Appended a missing underscore so the link works correctly.
=> Fix link markup in the documentation

tests/test_cli.py, tests/test_config.py, yamllint/config.py
Previously, these errors used the word "dict" because it's the common term in the Python world. But the YAML term is rather "mapping". The present commit fixes this wording.
This originates from this discussion [^2].
[^1]: https://yaml.org/spec/1.2.2/#3211-nodes
[^2]: https://github.com/adrienverge/yamllint/pull/747#pullrequestreview-2813393998
=> config: Use "mapping" instead of "dict" for user-facing errors

pyproject.toml
In the current version, `pip install .` emits the following warnings:
```
********************************************************************************
Please use a simple string containing a SPDX expression for `project.license`. You can also use `project.license-files`. (Both options available on setuptools>=77.0.0).
By 2026-Feb-18, you need to update your project and remove deprecated calls
or your builds will no longer be supported.
See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
********************************************************************************
```
```
********************************************************************************
Please consider removing the following classifiers in favor of a SPDX license expression: …
```
=> Fix deprecated license specification format

.github/workflows/tests.yaml, docs/conf.py, pyproject.toml, tests/__init__.py, tests/common.py, tests/rules/test_line_length.py, tests/test_cli.py, tests/test_config.py, tests/test_decoder.py, yamllint/cli.py, yamllint/config.py, yamllint/rules/indentation.py, yamllint/rules/key_ordering.py, yamllint/rules/line_length.py, yamllint/rules/quoted_strings.py, yamllint/rules/trailing_spaces.py
Implement https://github.com/adrienverge/yamllint/pull/716#issuecomment-2740687520.
Requires #759 to be applied first.
=> style: Enforce ruff rules

yamllint/rules/quoted_strings.py
Commit e3d54cc was missing a reference to the new `consistent` functionality in `quote-type`.
Thanks to @kleinschrader in adrienverge/yamllint#776 for noticing this.
=> quoted-strings: Add missing quote-type: consistent docs
